reviewers:
  # The default core reviewers.
  # Reviews may only be requested from collaborators.
  defaults:
    - SofyaKirillova
    - DaniilMaslovSaritasa
    - artem-sotnichenko-saritasa
    - pavel-romanov8
    - TienLuu-Saritasa
